export const DEL_USER = "DEL_USER";
export const ADD_USER = "ADD_USER";
export const USER_REQUEST_LOGIN = "USER_REQUEST_LOGIN"
export const USER_REQUEST_LOGIN_SUCCESS = "USER_REQUEST_LOGIN_SUCCESS"
export const USER_REQUEST_LOGIN_FAIL = "USER_REQUEST_LOGIN_FAIL"

export const USER_REQUEST_REGISTR = "USER_REQUEST_REGISTR"
export const USER_REQUEST_REGISTR_SUCCESS = "USER_REQUEST_REGISTR_SUCCESS"
export const USER_REQUEST_REGISTR_FAIL = "USER_REQUEST_REGISTR_FAIL"
export const USER_REQUEST_AUTHORIZATION = "USER_REQUEST_AUTHORIZATION"
export const USER_REQUEST_AUTHORIZATION_SUCCESS = "USER_REQUEST_AUTHORIZATION_SUCCESS"
export const USER_REQUEST_AUTHORIZATION_FAIL = "USER_REQUEST_AUTHORIZATION_FAIL"

export const SET_USER_TO_UPDATE = "SET_USER_TO_UPDATE";
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SAVE_REQUEST = "UPDATE_USER_SAVE_REQUEST"
export const UPDATE_USER_SAVE_REQUEST_SUCCESS = "UPDATE_USER_SAVE_REQUEST_SUCCESS"
export const UPDATE_USER_SAVE_REQUEST_FAIL = "UPDATE_USER_SAVE_REQUEST_FAIL"

export const GET_ALL_POSTS = "GET_ALL_POSTS"
export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_REQUEST_SUCCESS = "GET_ALL_POSTS_REQUEST_SUCCESS"
export const GET_ALL_POSTS_REQUEST_FAIL = "GET_ALL_POSTS_REQUEST_FAIL"

export const GET_ALL_MY_POSTS_REQUEST = "GET_ALL_MY_POSTS_REQUEST"
export const GET_ALL_MY_POSTS_REQUEST_SUCCESS = "GET_ALL_MY_POSTS_REQUEST_SUCCESS"
export const GET_ALL_MY_POSTS_REQUEST_FAIL = "GET_ALL_MY_POSTS_REQUEST_FAIL"

export const ADD_LIKE = "ADD_LIKE"
export const ADD_LIKE_REQUEST = "ADD_LIKE_REQUEST"
export const ADD_LIKE_REQUEST_SUCCESS = "ADD_LIKE_REQUEST_SUCCESS"
export const DEL_LIKE = "DEL_LIKE"
export const DEL_LIKE_REQUEST = "DEL_LIKE_REQUEST"
export const DEL_LIKE_REQUEST_SUCCESS = "DEL_LIKE_REQUEST_SUCCESS"