export const DEL_USER = "DEL_USER";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SETINGS_REQUEST = "ADD_USER_SETINGS_REQUEST";
export const ADD_USER_SETINGS_REQUEST_SUCCESS = "ADD_USER_SETINGS_REQUEST_SUCCESS";
export const ADD_USER_SETINGS_REQUEST_FAIL = "ADD_USER_SETINGS_REQUEST_FAIL";

export const USER_REQUEST_LOGIN = "USER_REQUEST_LOGIN"
export const USER_REQUEST_LOGIN_SUCCESS = "USER_REQUEST_LOGIN_SUCCESS"
export const USER_REQUEST_LOGIN_FAIL = "USER_REQUEST_LOGIN_FAIL"

export const USER_REQUEST_REGISTR = "USER_REQUEST_REGISTR"
export const USER_REQUEST_REGISTR_SUCCESS = "USER_REQUEST_REGISTR_SUCCESS"
export const USER_REQUEST_REGISTR_FAIL = "USER_REQUEST_REGISTR_FAIL"

export const USER_UPSERT_NICK_REQUEST = "USER_UPSERT_NICK_REQUEST"
export const USER_UPSERT_NICK_REQUEST_SUCCESS = "USER_UPSERT_NICK_REQUEST_SUCCESS"
export const USER_UPSERT_NICK_REQUEST_FAIL = "USER_UPSERT_NICK_REQUEST_FAIL"
export const USER_UPSERT_AVATAR_REQUEST = "USER_UPSERT_AVATAR_REQUEST"
export const USER_UPSERT_AVATAR_REQUEST_SUCCESS = "USER_UPSERT_AVATAR_REQUEST_SUCCESS"
export const USER_UPSERT_AVATAR_REQUEST_FAIL = "USER_UPSERT_AVATAR_REQUEST_FAIL"

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_REQUEST_SUCCESS = "GET_ALL_POSTS_REQUEST_SUCCESS"
export const GET_ALL_POSTS_REQUEST_FAIL = "GET_ALL_POSTS_REQUEST_FAIL"

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_REQUEST_SUCCESS = "GET_POST_REQUEST_SUCCESS"
export const GET_POST_REQUEST_FAIL = "GET_POST_REQUEST_FAIL"

export const LOAD_POSTS_REQUEST = "LOAD_POSTS_REQUEST"
export const LOAD_POSTS_REQUEST_SUCCESS = "LOAD_POSTS_REQUEST_SUCCESS"
export const LOAD_POSTS_REQUEST_FAIL = "LOAD_POSTS_REQUEST_FAIL"

export const GET_ALL_MY_POSTS_REQUEST = "GET_ALL_MY_POSTS_REQUEST"
export const GET_ALL_MY_POSTS_REQUEST_SUCCESS = "GET_ALL_MY_POSTS_REQUEST_SUCCESS"
export const GET_ALL_MY_POSTS_REQUEST_FAIL = "GET_ALL_MY_POSTS_REQUEST_FAIL"

export const REFRESH_POST_REQUEST = "REFRESH_POST_REQUEST"
export const REFRESH_POST_REQUEST_SUCCESS = "REFRESH_POST_REQUEST_SUCCESS"

export const ADD_LIKE = "ADD_LIKE"
export const ADD_LIKE_REQUEST = "ADD_LIKE_REQUEST"
export const ADD_LIKE_REQUEST_SUCCESS = "ADD_LIKE_REQUEST_SUCCESS"
export const DEL_LIKE = "DEL_LIKE"
export const DEL_LIKE_REQUEST = "DEL_LIKE_REQUEST"
export const DEL_LIKE_REQUEST_SUCCESS = "DEL_LIKE_REQUEST_SUCCESS"

export const ALL_USERS = "ALL_USERS"
export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST"
export const LOAD_USERS_REQUEST_SUCCESS = "LOAD_USERS_REQUEST_SUCCESS"
export const LOAD_USERS_REQUEST_FAIL = "LOAD_USERS_REQUEST_FAIL"

export const CREATE_NEW_POST_REQUEST = "CREATE_NEW_POST_REQUEST"
export const CREATE_NEW_POST_REQUEST_SUCCESS = "CREATE_NEW_POST_REQUEST_SUCCESS"
export const CREATE_NEW_POST_REQUEST_FAIL = "CREATE_NEW_POST_REQUEST_FAIL"