export const DEL_USER = "DEL_USER";
export const ADD_USER = "ADD_USER";
export const DEL_POSTS = "DEL_POSTS";
export const DEL_SEARCH = "DEL_SEARCH";
export const ADD_USER_SETINGS_REQUEST = "ADD_USER_SETINGS_REQUEST";
export const ADD_USER_SETINGS_REQUEST_SUCCESS = "ADD_USER_SETINGS_REQUEST_SUCCESS";
export const ADD_USER_SETINGS_REQUEST_FAIL = "ADD_USER_SETINGS_REQUEST_FAIL";

export const USER_REQUEST_LOGIN = "USER_REQUEST_LOGIN"
export const USER_REQUEST_LOGIN_SUCCESS = "USER_REQUEST_LOGIN_SUCCESS"
export const USER_REQUEST_LOGIN_FAIL = "USER_REQUEST_LOGIN_FAIL"

export const USER_REQUEST_REGISTR = "USER_REQUEST_REGISTR"
export const USER_REQUEST_REGISTR_SUCCESS = "USER_REQUEST_REGISTR_SUCCESS"
export const USER_REQUEST_REGISTR_FAIL = "USER_REQUEST_REGISTR_FAIL"

export const USER_UPSERT_NICK_REQUEST = "USER_UPSERT_NICK_REQUEST"
export const USER_UPSERT_NICK_REQUEST_SUCCESS = "USER_UPSERT_NICK_REQUEST_SUCCESS"
export const USER_UPSERT_NICK_REQUEST_FAIL = "USER_UPSERT_NICK_REQUEST_FAIL"
export const USER_UPSERT_AVATAR_REQUEST = "USER_UPSERT_AVATAR_REQUEST"
export const USER_UPSERT_AVATAR_REQUEST_SUCCESS = "USER_UPSERT_AVATAR_REQUEST_SUCCESS"
export const USER_UPSERT_AVATAR_REQUEST_FAIL = "USER_UPSERT_AVATAR_REQUEST_FAIL"
export const USER_UPSERT_FOLLOWING_REQUEST = "USER_UPSERT_FOLLOWING_REQUEST"
export const USER_UPSERT_FOLLOWING_REQUEST_SUCCESS = "USER_UPSERT_FOLLOWING_REQUEST_SUCCESS"
export const USER_UPSERT_FOLLOWING_REQUEST_FAIL = "USER_UPSERT_FOLLOWING_REQUEST_FAIL"

export const DEL_MY_POSTS = "DEL_MY_POSTS"
export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_REQUEST_SUCCESS = "GET_ALL_POSTS_REQUEST_SUCCESS"
export const GET_ALL_POSTS_REQUEST_FAIL = "GET_ALL_POSTS_REQUEST_FAIL"

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_REQUEST_SUCCESS = "GET_POST_REQUEST_SUCCESS"
export const GET_POST_REQUEST_FAIL = "GET_POST_REQUEST_FAIL"

export const LOAD_POSTS_REQUEST = "LOAD_POSTS_REQUEST"
export const LOAD_POSTS_REQUEST_SUCCESS = "LOAD_POSTS_REQUEST_SUCCESS"
export const LOAD_POSTS_REQUEST_FAIL = "LOAD_POSTS_REQUEST_FAIL"

export const GET_ALL_MY_POSTS_REQUEST = "GET_ALL_MY_POSTS_REQUEST"
export const GET_ALL_MY_POSTS_REQUEST_SUCCESS = "GET_ALL_MY_POSTS_REQUEST_SUCCESS"
export const GET_ALL_MY_POSTS_REQUEST_FAIL = "GET_ALL_MY_POSTS_REQUEST_FAIL"

export const REFRESH_POST_REQUEST = "REFRESH_POST_REQUEST"
export const REFRESH_POST_REQUEST_SUCCESS = "REFRESH_POST_REQUEST_SUCCESS"


export const ADD_LIKE_REQUEST = "ADD_LIKE_REQUEST"
export const ADD_LIKE_REQUEST_SUCCESS = "ADD_LIKE_REQUEST_SUCCESS"

export const DEL_LIKE_REQUEST = "DEL_LIKE_REQUEST"
export const DEL_LIKE_REQUEST_SUCCESS = "DEL_LIKE_REQUEST_SUCCESS"
export const ADD_LIKE_POSTS_REQUEST = "ADD_LIKE_POSTS_REQUEST"
export const ADD_LIKE_POSTS_REQUEST_SUCCESS = "ADD_LIKE_POSTS_REQUEST_SUCCESS"

export const DEL_LIKE_POSTS_REQUEST = "DEL_LIKE_POSTS_REQUEST"
export const DEL_LIKE_POSTS_REQUEST_SUCCESS = "DEL_LIKE_POSTS_REQUEST_SUCCESS"

export const ALL_USERS = "ALL_USERS"
export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST"
export const LOAD_USERS_REQUEST_SUCCESS = "LOAD_USERS_REQUEST_SUCCESS"
export const LOAD_USERS_REQUEST_FAIL = "LOAD_USERS_REQUEST_FAIL"

export const CREATE_NEW_POST_REQUEST = "CREATE_NEW_POST_REQUEST"
export const CREATE_NEW_POST_REQUEST_SUCCESS = "CREATE_NEW_POST_REQUEST_SUCCESS"
export const CREATE_NEW_POST_REQUEST_FAIL = "CREATE_NEW_POST_REQUEST_FAIL"

export const ADD_NEW_COMMENT_REQUEST = "ADD_NEW_COMMENT_REQUEST"
export const ADD_NEW_COMMENT_REQUEST_SUCCESS = "ADD_NEW_COMMENT_REQUEST_SUCCESS"
export const ADD_NEW_COMMENT_REQUEST_FAIL = "ADD_NEW_COMMENT_REQUEST_FAIL"

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST"
export const EDIT_COMMENT_REQUEST_SUCCESS = "EDIT_COMMENT_REQUEST_SUCCESS"
export const EDIT_COMMENT_REQUEST_FAIL = "EDIT_COMMENT_REQUEST_FAIL"

export const ADD_LIKE_COMMENT_REQUEST = "ADD_LIKE_COMMENT_REQUEST"
export const ADD_LIKE_COMMENT_REQUEST_SUCCESS = "ADD_LIKE_COMMENT_REQUEST_SUCCESS"
export const ADD_LIKE_COMMENT_REQUEST_FAIL = "ADD_LIKE_COMMENT_REQUEST_FAIL"

export const DEL_LIKE_COMMENT_REQUEST = "DEL_LIKE_COMMENT_REQUEST"
export const DEL_LIKE_COMMENT_REQUEST_SUCCESS = "DEL_LIKE_COMMENT_REQUEST_SUCCESS"
export const DEL_LIKE_COMMENT_REQUEST_FAIL = "DEL_LIKE_COMMENT_REQUEST_FAIL"

export const REFRESH_MY_POST = "REFRESH_MY_POST"

export const SELECTED_USER_REQUEST = "SELECTED_USER_REQUEST"
export const SELECTED_USER_REQUEST_SUCCESS = "SELECTED_USER_REQUEST_SUCCESS"
export const SELECTED_USER_REQUEST_FAIL = "SELECTED_USER_REQUEST_FAIL"

export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER'

export const SEARCH_POSTS_REQUEST = 'SEARCH_POSTS_REQUEST'
export const SEARCH_POSTS_REQUEST_SUCCESS = 'SEARCH_POSTS_REQUEST_SUCCESS'
export const SEARCH_POSTS_REQUEST_FAIL = 'SEARCH_POSTS_REQUEST_FAIL'
export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST'
export const SEARCH_USER_REQUEST_SUCCESS = 'SEARCH_USER_REQUEST_SUCCESS'
export const SEARCH_USER_REQUEST_FAIL = 'SEARCH_USER_REQUEST_FAIL'